### ISSUE TITLE
Minor: console.logs() left in built version

### ISSUE THREAD

**Issue by mikemaccana** [Bonfida/sns-sdk#7]
When running unit tests: 

```
  console.log
    mint Avcptd1yzx67NnK8ed8g8HZGeg8vFZp6437cwSm3gQj6

      at F (node_modules/@bonfida/spl-name-service/dist/index.cjs:1:8742)

  console.log
    mint 6sLbLpia2LuH8jNyfgc1EEjeZkCTDmsfujhmzunkwnZ3

      at F (node_modules/@bonfida/spl-name-service/dist/index.cjs:1:8742)

  console.log
    mint 4QdW7gKBvYkfyGndoq2LJ4uJRAgdDFrgV336zdd86nDW

      at F (node_modules/@bonfida/spl-name-service/dist/index.cjs:1:8742)

  console.log
    mint 6sLbLpia2LuH8jNyfgc1EEjeZkCTDmsfujhmzunkwnZ3

      at F (node_modules/@bonfida/spl-name-service/dist/index.cjs:1:8742)
```

I can't find this in your code (searching for `mint ` doesn't find anything so maybe you just need to rebuild.

**Comment by dr497** [comment]
Thanks for flagging! Should be fixed in `0.2.12`
