### ISSUE TITLE
main/require index.cjs are defined in package.json, but not part of published dist

### ISSUE THREAD

**Issue by thepiwo** [Bonfida/sns-sdk#77]
the `package.json` defines:

```
  ...
  "main": "./dist/index.cjs",
  ...
  "exports": {
    ".": {
      "require": "./dist/index.cjs",
      ...
    }
  },
```
but the published dist doesn't seem to include this: https://www.npmjs.com/package/@bonfida/spl-name-service?activeTab=code

resulting in me trying to use it with tsx:
```
> tsx ./src/index.ts

node:internal/modules/cjs/loader:1070
  const err = new Error(`Cannot find module '${request}'`);
              ^

Error: Cannot find module '.../node_modules/@bonfida/spl-name-service/dist/index.cjs'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1070:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1063:15)
    at resolveExports (node:internal/modules/cjs/loader:547:14)
    at Module._findPath (node:internal/modules/cjs/loader:621:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1034:27)
    at nextResolveSimple (.../node_modules/tsx/dist/register-C1urN2EO.cjs:3:942)
    at .../node_modules/tsx/dist/register-C1urN2EO.cjs:2:2486
    at .../node_modules/tsx/dist/register-C1urN2EO.cjs:2:1560
    at resolveTsPaths (.../node_modules/tsx/dist/register-C1urN2EO.cjs:3:760)
    at .../node_modules/tsx/dist/register-C1urN2EO.cjs:3:1035 {
  code: 'MODULE_NOT_FOUND',
  path: '.../node_modules/@bonfida/spl-name-service/package.json'
}

Node.js v20.9.0
```
(replaced my absolute path with `...`)

**Comment by akashrdev** [comment]
Hi, thank you for raising this. We will look into it and update you.

**Comment by dr497** [comment]
@thepiwo Thank you for opening the issue. I believe this PR should fix the issue you have found https://github.com/Bonfida/sns-sdk/pull/79
